services:

  api:
    container_name: api-container
    build: .
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  celery_worker:
    container_name: celery-worker
    build: .
    command: python -m celery -A backend.celery_app worker --loglevel=info
    depends_on:
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  telegram_bot:
    container_name: tgbot
    build: .
    command: python app.py
    depends_on:
      - api
      - redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"